#!/usr/bin/env python3
"""gen-libidn2-table.py — generate the IDNA2008 derived-property table for
the bind9-rs-tools libidn2 compatibility module.

Source: the pinned libidn2 2.3.8 tree's generated `lib/data.c`
(bind9-rs-tools/forensics/oracle/work/deps/libidn2-2.3.8/lib/data.c),
which holds `const struct idna_table idna_table[]` — the IDNA2008 derived
property (PVALID/CONTEXTJ/CONTEXTO/DISALLOWED/UNASSIGNED) range table
generated by libidn2 from the Unicode IDNA derived data.

This is data extraction with provenance, not a reimplementation: the source
file's sha256 is embedded in the generated Rust so a drifted oracle baseline
is a forensic event (spec §62).

Usage: scripts/archaeology/gen-libidn2-table.py
Writes: bind9-rs-tools/src/compat/libidn2_data.rs
"""

import hashlib
import os
import re
import sys

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
SRC = os.path.join(
    REPO_ROOT,
    "bind9-rs-tools/forensics/oracle/work/deps/libidn2-2.3.8/lib/data.c",
)
OUT = os.path.join(REPO_ROOT, "bind9-rs-tools/src/compat/libidn2_data.rs")

if not os.path.exists(SRC):
    print(f"error: {SRC} not found (extract the libidn2 oracle source first)", file=sys.stderr)
    sys.exit(1)

with open(SRC, "rb") as f:
    raw = f.read()
sha = hashlib.sha256(raw).hexdigest()
text = raw.decode("utf-8")

STATES = {"PVALID": 0, "CONTEXTJ": 1, "CONTEXTO": 2, "DISALLOWED": 3, "UNASSIGNED": 4}

rows = []
for m in re.finditer(r"\{0x([0-9A-Fa-f]+),\s*0x([0-9A-Fa-f]+),\s*([A-Z]+)\}", text):
    start = int(m.group(1), 16)
    end = int(m.group(2), 16)
    state = STATES[m.group(3)]
    rows.append((start, end, state))

if not rows:
    print("error: no table rows parsed", file=sys.stderr)
    sys.exit(1)

# Sanity: rows must be sorted, non-overlapping, in range; gaps default to
# UNASSIGNED (libidn2 tables.c `property()`: bsearch miss -> UNASSIGNED).
prev_end = 0
for start, end, _state in rows:
    assert start <= end, (start, end)
    assert start >= prev_end, f"overlap at 0x{start:x}"
    assert end < 0x110000
    prev_end = end + 1

lines = [
    "// Generated by scripts/archaeology/gen-libidn2-table.py — DO NOT EDIT.",
    "//",
    "// IDNA2008 derived property table (PVALID / CONTEXTJ / CONTEXTO /",
    "// DISALLOWED / UNASSIGNED) extracted from the pinned libidn2 2.3.8",
    "// generated table lib/data.c.  The source file is part of the pinned",
    "// oracle source set (forensics/manifests/dependency-sources.json); its",
    "// sha256 is recorded below so a drifted baseline is detectable.",
    "//",
    f"// source: libidn2-2.3.8/lib/data.c",
    f"// source_sha256: {sha}",
    f"// rows: {len(rows)}",
    "",
    "#![allow(clippy::unreadable_literal)]",
    "",
    "/// IDNA2008 derived property states (libidn2 data.h enum order).",
    "#[derive(Clone, Copy, Debug, PartialEq, Eq)]",
    "#[repr(u8)]",
    "pub enum IdnaState {",
    "    Pvalid = 0,",
    "    ContextJ = 1,",
    "    ContextO = 2,",
    "    Disallowed = 3,",
    "    Unassigned = 4,",
    "}",
    "",
    "/// (start, end, state) range rows, covering 0x0000..0x10FFFF exactly.",
    "pub const IDNA_TABLE: &[(u32, u32, u8)] = &[",
]
for start, end, state in rows:
    lines.append(f"    (0x{start:04X}, 0x{end:04X}, {state}),")
lines += [
    "];",
    "",
    "/// Binary search of the range table; every code point is covered.",
    "pub fn property(cp: u32) -> IdnaState {",
    "    let mut lo = 0usize;",
    "    let mut hi = IDNA_TABLE.len();",
    "    while lo < hi {",
    "        let mid = (lo + hi) / 2;",
    "        let (start, end, state) = IDNA_TABLE[mid];",
    "        if cp < start {",
    "            hi = mid;",
    "        } else if cp > end {",
    "            lo = mid + 1;",
    "        } else {",
    "            return match state {",
    "                0 => IdnaState::Pvalid,",
    "                1 => IdnaState::ContextJ,",
    "                2 => IdnaState::ContextO,",
    "                3 => IdnaState::Disallowed,",
    "                _ => IdnaState::Unassigned,",
    "            };",
    "        }",
    "    }",
    "    // Unreachable: the table covers the whole code point space.",
    "    IdnaState::Unassigned",
    "}",
    "",
    "#[cfg(test)]",
    "mod tests {",
    "    use super::*;",
    "",
    "    #[test]",
    "    fn spot_checks_match_idna2008() {",
    "        // U+002D HYPHEN-MINUS is PVALID.",
    "        assert_eq!(property(0x002D), IdnaState::Pvalid);",
    "        // U+00B7 MIDDLE DOT is CONTEXTO (RFC 5892 A.4).",
    "        assert_eq!(property(0x00B7), IdnaState::ContextO);",
    "        // U+00DF LATIN SMALL LETTER SHARP S is PVALID.",
    "        assert_eq!(property(0x00DF), IdnaState::Pvalid);",
    "        // U+00AD SOFT HYPHEN is DISALLOWED (removed by TR46 before the",
    "        // label test, so it never surfaces as an error).",
    "        assert_eq!(property(0x00AD), IdnaState::Disallowed);",
    "        // U+200C/U+200D are CONTEXTJ (RFC 5892 A.1/A.2).",
    "        assert_eq!(property(0x200C), IdnaState::ContextJ);",
    "        assert_eq!(property(0x200D), IdnaState::ContextJ);",
    "        // U+1F600 (emoji) is DISALLOWED in IDNA2008 — the exact",
    "        // libidn2 behavior dig relies on (dighost.c comment).",
    "        assert_eq!(property(0x1F600), IdnaState::Disallowed);",
    "        // U+0600 ARABIC NUMBER SIGN is DISALLOWED.",
    "        assert_eq!(property(0x0600), IdnaState::Disallowed);",
    "        // U+FFFD REPLACEMENT CHARACTER is DISALLOWED.",
    "        assert_eq!(property(0xFFFD), IdnaState::Disallowed);",
    "    }",
    "}",
    "",
]

with open(OUT, "w") as f:
    f.write("\n".join(lines))

print(f"wrote {OUT}: {len(rows)} rows, source sha256 {sha}")
