#!/usr/bin/env python3
"""gen-libidn2-tr46map.py — generate the UTS #46 mapping table for the
bind9-rs-tools libidn2 compatibility module.

Source: the pinned libidn2 2.3.8 tree's generated `lib/tr46map_data.c`
(bind9-rs-tools/forensics/oracle/work/deps/libidn2-2.3.8/lib/tr46map_data.c),
holding `idna_flags`, `idna_map_8/16/24` (compressed (cp1, range, value)
rows) and `mapdata` (the LEB128-style mapping payload).  The decode rules
are those of `tr46map.c` `_fill_map`/`get_map_data`: each row is 5 bytes
(cp<=0xFF), 7 bytes (cp<=0xFFFF) or 8 bytes (cp<=0xFFFFFF) of
cp1|range|value, with value = (nmappings << 14 | offset) << 3 | flag_index.

This is data extraction with provenance, not a reimplementation: the source
file's sha256 is embedded in the generated Rust so a drifted oracle baseline
is a forensic event (spec §62).

Usage: scripts/archaeology/gen-libidn2-tr46map.py
Writes: bind9-rs-tools/src/compat/libidn2_tr46map.rs
"""

import hashlib
import os
import re
import sys

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
SRC = os.path.join(
    REPO_ROOT,
    "bind9-rs-tools/forensics/oracle/work/deps/libidn2-2.3.8/lib/tr46map_data.c",
)
OUT = os.path.join(REPO_ROOT, "bind9-rs-tools/src/compat/libidn2_tr46map.rs")

if not os.path.exists(SRC):
    print(f"error: {SRC} not found (extract the libidn2 oracle source first)", file=sys.stderr)
    sys.exit(1)

with open(SRC, "rb") as f:
    raw = f.read()
sha = hashlib.sha256(raw).hexdigest()
text = raw.decode("utf-8")


def parse_array(name):
    m = re.search(rf"static const uint8_t {name}\[(\d+)\]\s*=\s*\{{(.*?)\}};", text, re.S)
    if not m:
        print(f"error: array {name} not found", file=sys.stderr)
        sys.exit(1)
    n = int(m.group(1))
    vals = [int(x, 16) for x in re.findall(r"0x([0-9A-Fa-f]+)", m.group(2))]
    if len(vals) != n:
        print(f"error: {name} parsed {len(vals)} values, expected {n}", file=sys.stderr)
        sys.exit(1)
    return vals


flags = parse_array("idna_flags")
map_8 = parse_array("idna_map_8")
map_16 = parse_array("idna_map_16")
map_24 = parse_array("idna_map_24")
mapdata = parse_array("mapdata")


def decode_rows(blob, rowlen, cpsize):
    """Decode (cp1, range, flag_index, offset, nmappings) rows."""
    rows = []
    for i in range(0, len(blob), rowlen):
        row = blob[i : i + rowlen]
        if cpsize == 1:
            cp1, rng = row[0], row[1]
        elif cpsize == 2:
            cp1 = (row[0] << 8) | row[1]
            rng = (row[2] << 8) | row[3]
        else:
            cp1 = (row[0] << 16) | (row[1] << 8) | row[2]
            rng = (row[3] << 8) | row[4]
        value = (row[-3] << 16) | (row[-2] << 8) | row[-1]
        flag_index = value & 0x7
        offset = (value >> 3) & 0x3FFF
        nmappings = (value >> 17) & 0x1F
        rows.append((cp1, rng, flag_index, offset, nmappings))
    return rows


rows8 = decode_rows(map_8, 5, 1)
rows16 = decode_rows(map_16, 7, 2)
rows24 = decode_rows(map_24, 8, 3)

out = []
out.append("// Generated by scripts/archaeology/gen-libidn2-tr46map.py — DO NOT EDIT.")
out.append("//")
out.append("// UTS #46 IDNA mapping table (valid/mapped/ignored/deviation/")
out.append("// disallowed/disallowed-std3-*) extracted from the pinned libidn2")
out.append("// 2.3.8 generated table lib/tr46map_data.c plus the decode rules of")
out.append("// lib/tr46map.c (`_fill_map`, `get_map_data`, `map_is`).  The source")
out.append("// file is part of the pinned oracle source set; its sha256 is")
out.append("// recorded below so a drifted baseline is detectable.")
out.append("")
out.append("// source: libidn2-2.3.8/lib/tr46map_data.c")
out.append(f"// source_sha256: {sha}")
out.append("//")
out.append(f"// rows: {len(rows8) + len(rows16) + len(rows24)}  mapdata bytes: {len(mapdata)}")
out.append("")
out.append("#![allow(clippy::unreadable_literal)]")
out.append("")
out.append("/// `TR46_FLG_*` (tr46map.h:35).")
out.append("#[derive(Clone, Copy, Debug, PartialEq, Eq)]")
out.append("#[repr(u32)]")
out.append("pub enum Flag {")
out.append("    Valid = 1,")
out.append("    Mapped = 2,")
out.append("    Ignored = 4,")
out.append("    Deviation = 8,")
out.append("    Disallowed = 16,")
out.append("    DisallowedStd3Mapped = 32,")
out.append("    DisallowedStd3Valid = 64,")
out.append("}")
out.append("")
out.append("/// One decoded row of `idna_map_8/16/24` (tr46map.c `_fill_map`).")
out.append("#[derive(Clone, Copy, Debug, PartialEq, Eq)]")
out.append("pub struct IdnaMap {")
out.append("    pub cp1: u32,")
out.append("    pub range: u32,")
out.append("    pub flag_index: u32,")
out.append("    pub offset: usize,")
out.append("    pub nmappings: u32,")
out.append("}")
out.append("")
out.append("/// `idna_flags[7]` (`tr46map_data.c`).")
out.append(f"pub const IDNA_FLAGS: [u32; {len(flags)}] = [")
for i in range(0, len(flags), 8):
    out.append("    " + ", ".join(str(x) for x in flags[i : i + 8]) + ",")
out.append("];")
out.append("")
out.append("/// `idna_map_8`: (`cp1`, `range`, `flag_index`, `offset`, `nmappings`) rows.")
out.append(f"pub const IDNA_MAP_8: &[(u32, u32, u32, usize, u32)] = &[")
for r in rows8:
    out.append(f"    ({r[0]}, {r[1]}, {r[2]}, {r[3]}, {r[4]}),")
out.append("];")
out.append("")
out.append("/// `idna_map_16`: (`cp1`, `range`, `flag_index`, `offset`, `nmappings`) rows.")
out.append(f"pub const IDNA_MAP_16: &[(u32, u32, u32, usize, u32)] = &[")
for r in rows16:
    out.append(f"    ({r[0]}, {r[1]}, {r[2]}, {r[3]}, {r[4]}),")
out.append("];")
out.append("")
out.append("/// `idna_map_24`: (`cp1`, `range`, `flag_index`, `offset`, `nmappings`) rows.")
out.append(f"pub const IDNA_MAP_24: &[(u32, u32, u32, usize, u32)] = &[")
for r in rows24:
    out.append(f"    ({r[0]}, {r[1]}, {r[2]}, {r[3]}, {r[4]}),")
out.append("];")
out.append("")
out.append("/// `mapdata`: the LEB128-style mapping payload (tr46map.c `get_map_data`).")
out.append(f"pub const MAPDATA: &[u8] = &[")
for i in range(0, len(mapdata), 24):
    out.append("    " + ", ".join(str(x) for x in mapdata[i : i + 24]) + ",")
out.append("];")

with open(OUT, "w") as f:
    f.write("\n".join(out) + "\n")
print(f"wrote {OUT}: {len(rows8) + len(rows16) + len(rows24)} rows, {len(mapdata)} mapdata bytes")
