//! `libcap` conservation module (addendum §27, §37, §38) — a native Rust
//! implementation of the libcap 2.78 C API surface with forensic fidelity.
//!
//! This is NOT a generic capability library.  It conserves libcap's
//! observable behavior as the BIND ecosystem relies on it:
//!
//! - the `cap_t` model: three flag sets (E/P/I) over 64 bits, v3 header,
//!   `rootid` (namespace owner) — `libcap/cap_alloc.c`, `libcap.h`;
//! - the text grammar of `cap_from_text`/`cap_to_text` including the
//!   archived quirks (the `=+`/`=-` ops, the "= "→"name=..." merge, the
//!   `%`/`^`/`!` IAB prefixes, the `all` keyword, numeric capabilities, the
//!   case-insensitive `cap_`-prefixed names) — `libcap/cap_text.c`;
//! - the external (portable) byte format of `cap_copy_ext`/`cap_copy_int`
//!   (magic `90 c2 01 51`) — `libcap/cap_extint.c`;
//! - the VFS file-capability xattr format (revisions 1/2/3, effective-bit
//!   encoding) — `libcap/cap_file.c`;
//! - the process operations (capget/capset, prctl bounding/ambient,
//!   secbits, modes, setuid/setgroups) — `libcap/cap_proc.c`.
//!
//! The kernel-touching calls live behind the audited `platform::linux`
//! boundary (unsafe inventory U-0001..U-0023, §49); everything else is safe
//! Rust.  Courts: `forensics/courts/cap-*` + the C probe
//! `forensics/oracle/probes/probe-libcap.c` (§37).
//!
//! Behavior IDs: CAP-NAME-*, CAP-TEXT-*, CAP-EXT-*, CAP-FLAG-*, CAP-FILE-*,
//! CAP-PROC-*, CAP-IAB-* (atlas: `bind9-rs-tools/forensics/atlas/doxygen/
//! libcap`).

use std::ffi::CString;

// ---------------------------------------------------------------------------
// Constants (kernel <uapi/linux/capability.h> + libcap.h)
// ---------------------------------------------------------------------------

/// The 41 named capabilities, `_cap_names` (generated by `_makenames.c` from
/// the kernel header: lowercase, WITH the `cap_` prefix — CAP-NAME-0001).
pub const CAP_NAMES: [&str; 41] = [
    "cap_chown",              // 0
    "cap_dac_override",       // 1
    "cap_dac_read_search",    // 2
    "cap_fowner",             // 3
    "cap_fsetid",             // 4
    "cap_kill",               // 5
    "cap_setgid",             // 6
    "cap_setuid",             // 7
    "cap_setpcap",            // 8
    "cap_linux_immutable",    // 9
    "cap_net_bind_service",   // 10
    "cap_net_broadcast",      // 11
    "cap_net_admin",          // 12
    "cap_net_raw",            // 13
    "cap_ipc_lock",           // 14
    "cap_ipc_owner",          // 15
    "cap_sys_module",         // 16
    "cap_sys_rawio",          // 17
    "cap_sys_chroot",         // 18
    "cap_sys_ptrace",         // 19
    "cap_sys_pacct",          // 20
    "cap_sys_admin",          // 21
    "cap_sys_boot",           // 22
    "cap_sys_nice",           // 23
    "cap_sys_resource",       // 24
    "cap_sys_time",           // 25
    "cap_sys_tty_config",     // 26
    "cap_mknod",              // 27
    "cap_lease",              // 28
    "cap_audit_write",        // 29
    "cap_audit_control",      // 30
    "cap_setfcap",            // 31
    "cap_mac_override",       // 32
    "cap_mac_admin",          // 33
    "cap_syslog",             // 34
    "cap_wake_alarm",         // 35
    "cap_block_suspend",      // 36
    "cap_audit_read",         // 37
    "cap_perfmon",            // 38
    "cap_bpf",                // 39
    "cap_checkpoint_restore", // 40
];

/// The number of named capabilities (`__CAP_BITS`, CAP_LAST_CAP + 1).
pub const CAP_BITS: usize = 41;

/// The maximum supportable capability bits (`__CAP_MAXBITS`, 2 × 32).
pub const CAP_MAX_BITS: usize = 64;

/// Capability values (`CAP_*`).
pub mod cap {
    pub const CHOWN: i32 = 0;
    pub const DAC_OVERRIDE: i32 = 1;
    pub const DAC_READ_SEARCH: i32 = 2;
    pub const FOWNER: i32 = 3;
    pub const FSETID: i32 = 4;
    pub const KILL: i32 = 5;
    pub const SETGID: i32 = 6;
    pub const SETUID: i32 = 7;
    pub const SETPCAP: i32 = 8;
    pub const LINUX_IMMUTABLE: i32 = 9;
    pub const NET_BIND_SERVICE: i32 = 10;
    pub const NET_BROADCAST: i32 = 11;
    pub const NET_ADMIN: i32 = 12;
    pub const NET_RAW: i32 = 13;
    pub const IPC_LOCK: i32 = 14;
    pub const IPC_OWNER: i32 = 15;
    pub const SYS_MODULE: i32 = 16;
    pub const SYS_RAWIO: i32 = 17;
    pub const SYS_CHROOT: i32 = 18;
    pub const SYS_PTRACE: i32 = 19;
    pub const SYS_PACCT: i32 = 20;
    pub const SYS_ADMIN: i32 = 21;
    pub const SYS_BOOT: i32 = 22;
    pub const SYS_NICE: i32 = 23;
    pub const SYS_RESOURCE: i32 = 24;
    pub const SYS_TIME: i32 = 25;
    pub const SYS_TTY_CONFIG: i32 = 26;
    pub const MKNOD: i32 = 27;
    pub const LEASE: i32 = 28;
    pub const AUDIT_WRITE: i32 = 29;
    pub const AUDIT_CONTROL: i32 = 30;
    pub const SETFCAP: i32 = 31;
    pub const MAC_OVERRIDE: i32 = 32;
    pub const MAC_ADMIN: i32 = 33;
    pub const SYSLOG: i32 = 34;
    pub const WAKE_ALARM: i32 = 35;
    pub const BLOCK_SUSPEND: i32 = 36;
    pub const AUDIT_READ: i32 = 37;
    pub const PERFMON: i32 = 38;
    pub const BPF: i32 = 39;
    pub const CHECKPOINT_RESTORE: i32 = 40;
}

/// The flag sets (`cap_flag_t`).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CapFlag {
    Effective = 0,
    Permitted = 1,
    Inheritable = 2,
}

/// A flag value (`cap_flag_value_t`).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CapFlagValue {
    Clear = 0,
    Set = 1,
}

/// libcap's `LIBCAP_EFF`/`LIBCAP_INH`/`LIBCAP_PER` bit values (also the
/// `cap_compare` result encoding, CAP-FLAG-0002).  Note the ordering:
/// `1 << CAP_EFFECTIVE(0)`, `1 << CAP_PERMITTED(1)`, `1 << CAP_INHERITABLE(2)`
/// — PER is *not* the 3rd bit.
pub const LIBCAP_EFF: i32 = 1 << 0;
pub const LIBCAP_PER: i32 = 1 << 1;
pub const LIBCAP_INH: i32 = 1 << 2;

/// `_LINUX_CAPABILITY_VERSION_3`.
pub const LINUX_CAPABILITY_VERSION_3: u32 = 0x2008_0522;
pub const LINUX_CAPABILITY_VERSION_2: u32 = 0x2007_1026;
pub const LINUX_CAPABILITY_VERSION_1: u32 = 0x1998_0330;

/// The external-format magic (`CAP_EXT_MAGIC` = `\220\302\001\121`,
/// CAP-EXT-0001).
pub const CAP_EXT_MAGIC: [u8; 4] = [0x90, 0xc2, 0x01, 0x51];

/// VFS_CAP_* (kernel <linux/capability.h>, CAP-FILE-0001).
pub const VFS_CAP_REVISION_MASK: u32 = 0xff00_0000;
pub const VFS_CAP_REVISION_1: u32 = 0x0100_0000;
pub const VFS_CAP_REVISION_2: u32 = 0x0200_0000;
pub const VFS_CAP_REVISION_3: u32 = 0x0300_0000;
pub const VFS_CAP_FLAGS_EFFECTIVE: u32 = 0x0000_0001;
pub const XATTR_CAPS_SZ_1: usize = 12;
pub const XATTR_CAPS_SZ_2: usize = 20;
pub const XATTR_CAPS_SZ_3: usize = 24;
pub const XATTR_NAME_CAPS: &str = "security.capability";

/// prctl options (libcap.h, CAP-PROC-0001).
pub const PR_SET_KEEPCAPS: i32 = 8;
pub const PR_CAPBSET_READ: i32 = 23;
pub const PR_CAPBSET_DROP: i32 = 24;
pub const PR_GET_SECUREBITS: i32 = 27;
pub const PR_SET_SECUREBITS: i32 = 28;
pub const PR_SET_NO_NEW_PRIVS: i32 = 38;
pub const PR_CAP_AMBIENT: i32 = 47;
pub const PR_CAP_AMBIENT_IS_SET: i32 = 1;
pub const PR_CAP_AMBIENT_RAISE: i32 = 2;
pub const PR_CAP_AMBIENT_LOWER: i32 = 3;
pub const PR_CAP_AMBIENT_CLEAR_ALL: i32 = 4;
pub const PR_SET_NAME: i32 = 15;

/// Securebits (CAP-PROC-0002).
pub const SECBIT_NOROOT: u32 = 1 << 0;
pub const SECBIT_NOROOT_LOCKED: u32 = 1 << 1;
pub const SECBIT_NO_SETUID_FIXUP: u32 = 1 << 2;
pub const SECBIT_NO_SETUID_FIXUP_LOCKED: u32 = 1 << 3;
pub const SECBIT_KEEP_CAPS: u32 = 1 << 4;
pub const SECBIT_KEEP_CAPS_LOCKED: u32 = 1 << 5;
pub const SECBIT_NO_CAP_AMBIENT_RAISE: u32 = 1 << 6;
pub const SECBIT_NO_CAP_AMBIENT_RAISE_LOCKED: u32 = 1 << 7;
const CAP_SECURED_BITS_BASIC: u32 = SECBIT_NOROOT
    | SECBIT_NOROOT_LOCKED
    | SECBIT_NO_SETUID_FIXUP
    | SECBIT_NO_SETUID_FIXUP_LOCKED
    | SECBIT_KEEP_CAPS_LOCKED;
const CAP_SECURED_BITS_AMBIENT: u32 =
    CAP_SECURED_BITS_BASIC | SECBIT_NO_CAP_AMBIENT_RAISE | SECBIT_NO_CAP_AMBIENT_RAISE_LOCKED;

/// Capability modes (`cap_mode_t`, CAP-PROC-0003).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CapMode {
    Uncertain = 0,
    NoPriv = 1,
    Pure1eInit = 2,
    Pure1e = 3,
    Hybrid = 4,
}

/// IAB vector identifiers (`cap_iab_vector_t`).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CapIabVector {
    Inh = 2,
    Amb = 3,
    Bound = 4,
}

// ---------------------------------------------------------------------------
// Errors (errno-modeled, CAP-ERR-0001)
// ---------------------------------------------------------------------------

/// A libc errno value as libcap surfaces it (`cap_get_errno`/`cap_set_errno`
/// in libcap's error model: each failing call stores errno; the caller reads
/// it back).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct CapErrno(pub i32);

impl CapErrno {
    pub const EINVAL: CapErrno = CapErrno(22);
    pub const ENOMEM: CapErrno = CapErrno(12);
    pub const ERANGE: CapErrno = CapErrno(34);
    pub const EPERM: CapErrno = CapErrno(1);
    pub const ENXIO: CapErrno = CapErrno(6);
}

impl std::fmt::Display for CapErrno {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "errno {}", self.0)
    }
}

/// The result type for the C-shaped API (the C functions return NULL/-1 and
/// set errno; the Rust equivalents return `Err(CapErrno)`).
pub type CapResult<T> = Result<T, CapErrno>;

// ---------------------------------------------------------------------------
// The cap_t model (CAP-ALLOC-0001)
// ---------------------------------------------------------------------------

/// The internal capability state (`struct _cap_struct`: three flat sets over
/// `__CAP_BLKS` 32-bit words + `rootid`).  `flat[set]` layout per block is
/// effective/permitted/inheritable (kernel `__user_cap_data_struct`).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CapState {
    /// Effective set, two 32-bit words.
    pub eff: [u32; 2],
    /// Permitted set, two 32-bit words.
    pub perm: [u32; 2],
    /// Inheritable set, two 32-bit words.
    pub inh: [u32; 2],
    /// The user-namespace root owner (`cap_d->rootid`, v3 only).
    pub rootid: u32,
}

impl Default for CapState {
    fn default() -> Self {
        Self::empty()
    }
}

impl CapState {
    /// `cap_init()`: a blank set with the v3 header (CAP-ALLOC-0002).
    #[must_use]
    pub fn empty() -> Self {
        CapState {
            eff: [0, 0],
            perm: [0, 0],
            inh: [0, 0],
            rootid: 0,
        }
    }

    /// `cap_dup()` (CAP-ALLOC-0003): a deep copy.
    #[must_use]
    pub fn dup(&self) -> Self {
        self.clone()
    }

    fn block_of(value: i32) -> usize {
        (value as usize) >> 5
    }

    fn mask_of(value: i32) -> u32 {
        1u32 << ((value as usize) & 31)
    }

    fn set(&mut self, set: CapFlag, value: i32) {
        let b = Self::block_of(value);
        match set {
            CapFlag::Effective => self.eff[b] |= Self::mask_of(value),
            CapFlag::Permitted => self.perm[b] |= Self::mask_of(value),
            CapFlag::Inheritable => self.inh[b] |= Self::mask_of(value),
        }
    }

    fn lower(&mut self, set: CapFlag, value: i32) {
        let b = Self::block_of(value);
        let m = !Self::mask_of(value);
        match set {
            CapFlag::Effective => self.eff[b] &= m,
            CapFlag::Permitted => self.perm[b] &= m,
            CapFlag::Inheritable => self.inh[b] &= m,
        }
    }

    fn isset(&self, set: CapFlag, value: i32) -> bool {
        let b = Self::block_of(value);
        let m = Self::mask_of(value);
        match set {
            CapFlag::Effective => self.eff[b] & m != 0,
            CapFlag::Permitted => self.perm[b] & m != 0,
            CapFlag::Inheritable => self.inh[b] & m != 0,
        }
    }

    fn flat(&self, set: CapFlag, block: usize) -> u32 {
        match set {
            CapFlag::Effective => self.eff[block],
            CapFlag::Permitted => self.perm[block],
            CapFlag::Inheritable => self.inh[block],
        }
    }

    fn set_flat(&mut self, set: CapFlag, block: usize, v: u32) {
        match set {
            CapFlag::Effective => self.eff[block] = v,
            CapFlag::Permitted => self.perm[block] = v,
            CapFlag::Inheritable => self.inh[block] = v,
        }
    }

    /// `cap_clear()` (CAP-FLAG-0001): zero every set.
    pub fn clear(&mut self) {
        self.eff = [0, 0];
        self.perm = [0, 0];
        self.inh = [0, 0];
    }

    /// `cap_clear_flag()` (CAP-FLAG-0002): zero one set.
    pub fn clear_flag(&mut self, flag: CapFlag) {
        for b in 0..2 {
            self.set_flat(flag, b, 0);
        }
    }

    /// `cap_get_flag()` (CAP-FLAG-0003).  Out-of-range values are EINVAL.
    pub fn get_flag(&self, value: i32, set: CapFlag) -> CapResult<CapFlagValue> {
        if value < 0 || value >= CAP_MAX_BITS as i32 {
            return Err(CapErrno::EINVAL);
        }
        Ok(if self.isset(set, value) {
            CapFlagValue::Set
        } else {
            CapFlagValue::Clear
        })
    }

    /// `cap_set_flag()` (CAP-FLAG-0004).  Per libcap, out-of-range entries in
    /// the array are *skipped* with no error; an empty or over-long array or
    /// a bad set/raise value is EINVAL (CAP-FLAG-0005).
    pub fn set_flag(&mut self, set: CapFlag, values: &[i32], raise: CapFlagValue) -> CapResult<()> {
        if values.is_empty() || values.len() >= CAP_MAX_BITS {
            return Err(CapErrno::EINVAL);
        }
        match set {
            CapFlag::Effective | CapFlag::Permitted | CapFlag::Inheritable => {}
        }
        match raise {
            CapFlagValue::Set | CapFlagValue::Clear => {}
        }
        for &v in values {
            if v < 0 || v >= CAP_MAX_BITS as i32 {
                // libcap: "weird capability - skipped"
                continue;
            }
            if raise == CapFlagValue::Set {
                self.set(set, v);
            } else {
                self.lower(set, v);
            }
        }
        Ok(())
    }

    /// `cap_fill_flag(cap_d, to, ref, from)` (CAP-FLAG-0006): copy one set of
    /// `ref` into `to` of self.
    pub fn fill_flag(&mut self, to: CapFlag, reference: &CapState, from: CapFlag) -> CapResult<()> {
        for b in 0..2 {
            let v = reference.flat(from, b);
            self.set_flat(to, b, v);
        }
        Ok(())
    }

    /// `cap_fill(cap_d, to, from)` (CAP-FLAG-0007): copy one set to another
    /// within the same state.
    pub fn fill(&mut self, to: CapFlag, from: CapFlag) -> CapResult<()> {
        let snapshot = self.dup();
        self.fill_flag(to, &snapshot, from)
    }

    /// `cap_compare(a, b)` (CAP-FLAG-0008): returns a bitmask of
    /// `LIBCAP_EFF | LIBCAP_INH | LIBCAP_PER` for the sets that differ.
    pub fn compare(&self, other: &CapState) -> i32 {
        let mut result = 0;
        for b in 0..2 {
            if self.eff[b] != other.eff[b] {
                result |= LIBCAP_EFF;
            }
            if self.inh[b] != other.inh[b] {
                result |= LIBCAP_INH;
            }
            if self.perm[b] != other.perm[b] {
                result |= LIBCAP_PER;
            }
        }
        result
    }
}

// ---------------------------------------------------------------------------
// Names (CAP-NAME-0001..0006)
// ---------------------------------------------------------------------------

/// `namcmp(str, nam)` (cap_text.c): case-insensitive prefix match; the match
/// is rejected when the character after the name is alphanumeric or `_`.
/// Returns the pointer past the matched name.
fn namcmp<'a>(s: &'a str, name: &str) -> Option<&'a str> {
    let mut chars = s.chars();
    for n in name.chars() {
        let c = chars.next()?;
        if c.to_ascii_lowercase() != n {
            return None;
        }
    }
    if let Some(next) = chars.clone().next() {
        if next.is_alphanumeric() || next == '_' {
            return None;
        }
    }
    Some(&s[name.len()..])
}

/// `lookupname` (cap_text.c): numeric (strtoul base 0 — hex `0x` accepted,
/// CAP-NAME-0004) or named (the `cap_`-prefixed `_cap_names`, matched
/// case-insensitively on the prefix; CAP-NAME-0001..0003).  The returned
/// string advances past the token (the numeric advance works through the
/// union aliasing of `str.constp`/`str.p` in the C — archived in
/// CAP-NAME-0005).
fn lookupname(s: &str) -> Option<(i32, &str)> {
    let first = s.chars().next()?;
    if first.is_ascii_digit() {
        // strtoul(s, &end, 0)
        let end = s
            .find(|c: char| {
                !(c.is_ascii_digit()
                    || c == 'x'
                    || c == 'X'
                    || ('a'..='f').contains(&c.to_ascii_lowercase())
                    || c == '0')
            })
            .unwrap_or(s.len());
        let (numstr, rest) = s.split_at(end);
        // re-validate: strtoul base 0 accepts decimal and 0x hex
        let n = if let Some(hex) = numstr
            .strip_prefix("0x")
            .or_else(|| numstr.strip_prefix("0X"))
        {
            u64::from_str_radix(hex, 16).ok()?
        } else {
            numstr.parse::<u64>().ok()?
        };
        if n >= CAP_MAX_BITS as u64 {
            return None;
        }
        // note: for "0x2" strtoul stops after "2"; for "5=ep" after "5"
        return Some((n as i32, rest));
    }
    for (idx, name) in CAP_NAMES.iter().enumerate() {
        if let Some(rest) = namcmp(s, name) {
            return Some((idx as i32, rest));
        }
    }
    None
}

/// `cap_from_name(name, &value)` (CAP-NAME-0006): returns Ok(value) when the
/// name parses; the C returns 0/-1.
pub fn cap_from_name(name: &str) -> CapResult<i32> {
    match lookupname(name) {
        Some((n, _)) => Ok(n),
        None => Err(CapErrno::EINVAL),
    }
}

/// `cap_to_name(cap)` (CAP-NAME-0007): the `cap_`-prefixed name for named
/// capabilities, otherwise the decimal rendering (`%u` of the value).
#[must_use]
pub fn cap_to_name(cap: i32) -> String {
    if (0..CAP_BITS as i32).contains(&cap) {
        CAP_NAMES[cap as usize].to_string()
    } else {
        // asprintf("%u", (unsigned)cap) — the C passes an int through %u.
        format!("{}", cap as u32)
    }
}

// ---------------------------------------------------------------------------
// Text form (CAP-TEXT-0001..0012)
// ---------------------------------------------------------------------------

fn is_name_char(c: char) -> bool {
    c.is_alphanumeric() || c == '_'
}

/// `cap_from_text(str)` (cap_text.c, CAP-TEXT-0001..0008): a faithful
/// transcription of the clause parser.
pub fn cap_from_text(text: &str) -> CapResult<CapState> {
    let mut res = CapState::empty();
    let mut s = text;

    loop {
        // skip leading spaces
        while let Some(c) = s.chars().next() {
            if c.is_whitespace() {
                s = &s[1..];
            } else {
                break;
            }
        }
        if s.is_empty() {
            return Ok(res);
        }

        let mut list = [0u32; 2];
        let mut listed = false;

        let first = s.chars().next().unwrap();
        if is_name_char(first) {
            loop {
                if let Some(rest) = namcmp(s, "all") {
                    s = rest;
                    forceall(&mut list, u32::MAX);
                } else {
                    let (n, rest) = match lookupname(s) {
                        Some(v) => v,
                        None => return Err(CapErrno::EINVAL),
                    };
                    s = rest;
                    list[(n as usize) >> 5] |= 1u32 << ((n as usize) & 31);
                }
                if !s.starts_with(',') {
                    break;
                }
                let after = &s[1..];
                if after.chars().next().map_or(true, |c| !is_name_char(c)) {
                    return Err(CapErrno::EINVAL);
                }
                s = after;
            }
            listed = true;
        } else if first == '+' || first == '-' {
            // "require a list of capabilities"
            return Err(CapErrno::EINVAL);
        } else {
            forceall(&mut list, u32::MAX);
        }

        // identify first operation
        let mut op = s.chars().next().unwrap();
        s = &s[1..];
        if op == '=' && s.starts_with('+') || (op == '=' && s.starts_with('-')) {
            if !listed {
                return Err(CapErrno::EINVAL);
            }
            op = if s.starts_with('+') { 'P' } else { 'M' }; // skip '='
            s = &s[1..];
        } else if op != '+' && op != '-' && op != '=' {
            return Err(CapErrno::EINVAL);
        }

        // cycle through list of actions; `flags` accumulates across flag
        // characters (cap_text.c declares it in the clause loop and resets it
        // only on a new +/- directive — CAP-TEXT-0003).
        let mut flags = 0i32;
        loop {
            let mut c = s.chars().next();
            match c {
                Some(ch) if !ch.is_whitespace() => {
                    match ch {
                        'e' => flags |= LIBCAP_EFF,
                        'i' => flags |= LIBCAP_INH,
                        'p' => flags |= LIBCAP_PER,
                        _ => return Err(CapErrno::EINVAL),
                    }
                    s = &s[1..];
                }
                // only '=' may be followed by whitespace or end-of-string
                // (cap_text.c: `else if (op != '=') goto bad;`)
                _ if op != '=' => return Err(CapErrno::EINVAL),
                _ => {}
            }

            match op {
                '=' | 'P' | 'M' => {
                    for b in 0..2 {
                        res.eff[b] &= !list[b];
                        res.perm[b] &= !list[b];
                        res.inh[b] &= !list[b];
                    }
                    if op != 'M' {
                        if flags & LIBCAP_EFF != 0 {
                            for b in 0..2 {
                                res.eff[b] |= list[b];
                            }
                        }
                        if flags & LIBCAP_PER != 0 {
                            for b in 0..2 {
                                res.perm[b] |= list[b];
                            }
                        }
                        if flags & LIBCAP_INH != 0 {
                            for b in 0..2 {
                                res.inh[b] |= list[b];
                            }
                        }
                    }
                }
                '+' => {
                    if flags & LIBCAP_EFF != 0 {
                        for b in 0..2 {
                            res.eff[b] |= list[b];
                        }
                    }
                    if flags & LIBCAP_PER != 0 {
                        for b in 0..2 {
                            res.perm[b] |= list[b];
                        }
                    }
                    if flags & LIBCAP_INH != 0 {
                        for b in 0..2 {
                            res.inh[b] |= list[b];
                        }
                    }
                }
                '-' => {
                    if flags & LIBCAP_EFF != 0 {
                        for b in 0..2 {
                            res.eff[b] &= !list[b];
                        }
                    }
                    if flags & LIBCAP_PER != 0 {
                        for b in 0..2 {
                            res.perm[b] &= !list[b];
                        }
                    }
                    if flags & LIBCAP_INH != 0 {
                        for b in 0..2 {
                            res.inh[b] &= !list[b];
                        }
                    }
                }
                _ => unreachable!(),
            }

            // new directive?
            if s.starts_with('+') || s.starts_with('-') {
                if !listed {
                    return Err(CapErrno::EINVAL);
                }
                flags = 0; // reset the flags (cap_text.c)
                op = s.chars().next().unwrap();
                s = &s[1..];
                if s.chars().next().map_or(true, |c| !c.is_alphabetic()) {
                    return Err(CapErrno::EINVAL);
                }
            } else if c.is_none() || s.chars().next().map_or(true, |c| c.is_whitespace()) {
                // end of this clause; the loop continues at the top-level
                // where whitespace is skipped and an empty string returns.
                break;
            }
        }
    }
}

/// `forceall` (cap_text.c): assign `value` to every named capability bit
/// (masked to `cap_max_bits()`), zero otherwise.
fn forceall(flat: &mut [u32; 2], value: u32) {
    let cmb = cap_max_bits();
    for (n, f) in flat.iter_mut().enumerate() {
        let base = 32 * n;
        let mask = if cmb >= base + 32 {
            u32::MAX
        } else if cmb > base {
            (1u64 << (cmb % 32)) as u32 - 1
        } else {
            0
        };
        *f = value & mask;
    }
}

fn getstateflags(caps: &CapState, capno: i32) -> i32 {
    let mut f = 0;
    if caps.isset(CapFlag::Effective, capno) {
        f |= LIBCAP_EFF;
    }
    if caps.isset(CapFlag::Permitted, capno) {
        f |= LIBCAP_PER;
    }
    if caps.isset(CapFlag::Inheritable, capno) {
        f |= LIBCAP_INH;
    }
    f
}

/// `cap_to_text(caps)` (cap_text.c, CAP-TEXT-0009..0012): the canonical text
/// form.  Returns (text, length) where length is `p - base` (after the "= "
/// merge).
#[must_use]
pub fn cap_to_text(caps: &CapState) -> (String, usize) {
    let cmb = cap_max_bits();
    let mut histo = [0usize; 8];
    for n in 0..cmb {
        histo[getstateflags(caps, n as i32) as usize] += 1;
    }
    // prevailing state: the most common combination, biased to 0.
    let mut m = 7usize;
    for t in (0..7).rev() {
        if histo[t] >= histo[m] {
            m = t;
        }
    }

    let mut buf = String::new();
    buf.push('=');
    if m & LIBCAP_EFF as usize != 0 {
        buf.push('e');
    }
    if m & LIBCAP_INH as usize != 0 {
        buf.push('i');
    }
    if m & LIBCAP_PER as usize != 0 {
        buf.push('p');
    }
    let mut base = 0usize; // index into buf where the returned text starts

    for t in (0..8).rev() {
        if t == m || histo[t] == 0 {
            continue;
        }
        buf.push(' ');
        for n in 0..cmb {
            if getstateflags(caps, n as i32) as usize == t {
                buf.push_str(&cap_to_name(n as i32));
                buf.push(',');
            }
        }
        buf.pop(); // remove trailing comma
        let add = t as i32 & !(m as i32);
        if add != 0 {
            let mut op = '+';
            if buf.as_bytes().get(base).copied() == Some(b'=')
                && buf.as_bytes().get(base + 1).copied() == Some(b' ')
            {
                // "= foo,...+eip ..." → "foo,...=eip ..." (equivalent, shorter)
                base += 2;
                op = '=';
            }
            buf.push(op);
            if add & LIBCAP_EFF != 0 {
                buf.push('e');
            }
            if add & LIBCAP_INH != 0 {
                buf.push('i');
            }
            if add & LIBCAP_PER != 0 {
                buf.push('p');
            }
        }
        let rem = !(t as i32) & m as i32;
        if rem != 0 {
            buf.push('-');
            if rem & LIBCAP_EFF != 0 {
                buf.push('e');
            }
            if rem & LIBCAP_INH != 0 {
                buf.push('i');
            }
            if rem & LIBCAP_PER != 0 {
                buf.push('p');
            }
        }
    }

    // remaining unnamed bits (cmb..64) — all must be +
    let mut histo2 = [0usize; 8];
    for n in cmb..CAP_MAX_BITS {
        histo2[getstateflags(caps, n as i32) as usize] += 1;
    }
    for t in (2..8).rev() {
        if histo2[t] == 0 {
            continue;
        }
        buf.push(' ');
        for n in cmb..CAP_MAX_BITS {
            if getstateflags(caps, n as i32) as usize == t {
                buf.push_str(&cap_to_name(n as i32));
                buf.push(',');
            }
        }
        buf.pop();
        buf.push('+');
        if t & LIBCAP_EFF as usize != 0 {
            buf.push('e');
        }
        if t & LIBCAP_INH as usize != 0 {
            buf.push('i');
        }
        if t & LIBCAP_PER as usize != 0 {
            buf.push('p');
        }
    }

    let len = buf.len() - base;
    (buf[base..].to_string(), len)
}

// ---------------------------------------------------------------------------
// External format (CAP-EXT-0001..0008)
// ---------------------------------------------------------------------------

/// `cap_size(cap_d)` (CAP-EXT-0001): the portable-format size in bytes.
#[must_use]
pub fn cap_size(caps: &CapState) -> usize {
    // _cap_size_locked: highest nonzero combined word, byte-rounded.
    let mut used = 0usize;
    for (j, _) in (0..8usize).step_by(4).enumerate() {
        let val = caps.eff[j / 4] | caps.perm[j / 4] | caps.inh[j / 4];
        if val == 0 {
            continue;
        }
        used = if val > 0x0000_ffff {
            if val > 0x00ff_ffff {
                j + 4
            } else {
                j + 3
            }
        } else if val > 0x0000_00ff {
            j + 2
        } else {
            j + 1
        };
    }
    if used < 8 {
        used = 8;
    }
    4 + 1 + 3 * used
}

/// `cap_copy_ext(ext, cap_d, length)` (CAP-EXT-0002): serialize into the
/// portable format; the destination must be at least `cap_size` bytes.
pub fn cap_copy_ext(dest: &mut [u8], caps: &CapState) -> CapResult<usize> {
    let csz = cap_size(caps);
    if dest.len() < csz {
        return Err(CapErrno::EINVAL);
    }
    let len_set = (csz - 5) / 3;
    dest[0..4].copy_from_slice(&CAP_EXT_MAGIC);
    dest[4] = len_set as u8;
    for (i, set) in [CapFlag::Effective, CapFlag::Permitted, CapFlag::Inheritable]
        .iter()
        .enumerate()
    {
        let mut j = 0usize;
        while j < len_set {
            // each u32 (byte offset j..j+4) comes from flat[set][j/4]
            let mut v = caps.flat(*set, j / 4);
            for k in 0..4 {
                if j + k < len_set {
                    dest[5 + (j + k) * 3 + i] = (v & 0xff) as u8;
                    v >>= 8;
                }
            }
            j += 4;
        }
    }
    Ok(csz)
}

/// `cap_copy_int(ext)` (CAP-EXT-0003): import the portable format (magic +
/// valid structure assumed, as the C does).
pub fn cap_copy_int(ext: &[u8]) -> CapResult<CapState> {
    if ext.len() < 5 || ext[0..4] != CAP_EXT_MAGIC {
        return Err(CapErrno::EINVAL);
    }
    let mut caps = CapState::empty();
    let blen = ext[4] as usize;
    for (i, set) in [CapFlag::Effective, CapFlag::Permitted, CapFlag::Inheritable]
        .iter()
        .enumerate()
    {
        let mut bno = 0usize;
        for blk in 0..2usize {
            // at most 4 bytes per u32, each guarded by bno != blen (the C
            // reads exactly 4 per block; the guard skips beyond blen).
            let mut val = 0u32;
            let mut shift = 0;
            for _ in 0..4 {
                if bno < blen {
                    let byte = *ext.get(5 + bno * 3 + i).unwrap_or(&0);
                    val |= (byte as u32) << shift;
                    bno += 1;
                }
                shift += 8;
            }
            caps.set_flat(*set, blk, val);
        }
    }
    Ok(caps)
}

/// `cap_copy_int_check(ext, length)` (CAP-EXT-0004): validate the length
/// against the declared set length before importing.
pub fn cap_copy_int_check(ext: &[u8]) -> CapResult<CapState> {
    if ext.len() < 5 {
        return Err(CapErrno::EINVAL);
    }
    let needed = 5 + ext[4] as usize * 3;
    if ext.len() < needed {
        return Err(CapErrno::EINVAL);
    }
    cap_copy_int(ext)
}

// ---------------------------------------------------------------------------
// IAB (CAP-IAB-0001..0008)
// ---------------------------------------------------------------------------

/// The IAB tuple (`cap_iab_s`): inheritable, ambient, and "drop from
/// bounding" vectors (CAP-IAB-0001).
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct CapIab {
    pub i: [u32; 2],
    pub a: [u32; 2],
    pub nb: [u32; 2],
}

impl CapIab {
    /// `cap_iab_init()`.
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }

    /// `cap_iab_get_vector` (CAP-IAB-0002): 0 when out of range.
    #[must_use]
    pub fn get_vector(&self, vec: CapIabVector, bit: i32) -> CapFlagValue {
        if bit < 0 || bit as usize >= cap_max_bits() {
            return CapFlagValue::Clear;
        }
        let o = (bit as usize) >> 5;
        let mask = 1u32 << (bit & 31);
        let v = match vec {
            CapIabVector::Inh => self.i[o] & mask,
            CapIabVector::Amb => self.a[o] & mask,
            CapIabVector::Bound => self.nb[o] & mask,
        };
        if v != 0 {
            CapFlagValue::Set
        } else {
            CapFlagValue::Clear
        }
    }

    /// `cap_iab_set_vector` (CAP-IAB-0003): setting A implies I; lowering I
    /// lowers A; B is independent.
    pub fn set_vector(
        &mut self,
        vec: CapIabVector,
        bit: i32,
        raised: CapFlagValue,
    ) -> CapResult<()> {
        if bit < 0 || bit as usize >= cap_max_bits() {
            return Err(CapErrno::EINVAL);
        }
        if !matches!(raised, CapFlagValue::Set | CapFlagValue::Clear) {
            return Err(CapErrno::EINVAL);
        }
        let o = (bit as usize) >> 5;
        let on = 1u32 << (bit & 31);
        let mask = !on;
        match vec {
            CapIabVector::Inh => {
                self.i[o] = (self.i[o] & mask) | if raised == CapFlagValue::Set { on } else { 0 };
                self.a[o] &= self.i[o];
            }
            CapIabVector::Amb => {
                self.a[o] = (self.a[o] & mask) | if raised == CapFlagValue::Set { on } else { 0 };
                self.i[o] |= self.a[o];
            }
            CapIabVector::Bound => {
                self.nb[o] = (self.nb[o] & mask) | if raised == CapFlagValue::Set { on } else { 0 };
            }
        }
        Ok(())
    }

    /// `cap_iab_fill` (CAP-IAB-0004): copy a cap_t flag vector into an IAB
    /// vector (bounding bits are inverted — "to be dropped").
    pub fn fill(&mut self, vec: CapIabVector, caps: &CapState, flag: CapFlag) -> CapResult<()> {
        for i in 0..2 {
            match vec {
                CapIabVector::Inh => {
                    self.i[i] = caps.flat(flag, i);
                    self.a[i] &= self.i[i];
                }
                CapIabVector::Amb => {
                    self.a[i] = caps.flat(flag, i);
                    self.i[i] |= caps.flat(flag, i);
                }
                CapIabVector::Bound => {
                    self.nb[i] = !caps.flat(flag, i);
                }
            }
        }
        Ok(())
    }

    /// `cap_iab_compare` (CAP-IAB-0005): bitmask of `1 << vector` for each
    /// differing vector.
    #[must_use]
    pub fn compare(&self, other: &CapIab) -> i32 {
        let mut result = 0;
        for j in 0..2 {
            if self.i[j] != other.i[j] {
                result |= 1 << (CapIabVector::Inh as i32);
            }
            if self.a[j] != other.a[j] {
                result |= 1 << (CapIabVector::Amb as i32);
            }
            if self.nb[j] != other.nb[j] {
                result |= 1 << (CapIabVector::Bound as i32);
            }
        }
        result
    }
}

/// `cap_iab_to_text` (cap_text.c, CAP-IAB-0006): `,`-separated `!`/`^`/`%`
/// prefixed names.
#[must_use]
pub fn cap_iab_to_text(iab: &CapIab) -> String {
    let cmb = cap_max_bits();
    let mut out = String::new();
    let mut first = true;
    for c in 0..cmb {
        let o = c >> 5;
        let bit = 1u32 << (c & 31);
        let ib = iab.i[o] & bit;
        let ab = iab.a[o] & bit;
        let nbb = iab.nb[o] & bit;
        if nbb | ab | ib == 0 {
            continue;
        }
        if !first {
            out.push(',');
        }
        let mut keep = false;
        if nbb != 0 {
            out.push('!');
            keep = true;
        }
        if ab != 0 {
            out.push('^');
            keep = true;
        } else if nbb != 0 && ib != 0 {
            out.push('%');
        }
        if keep || ib != 0 {
            out.push_str(&cap_to_name(c as i32));
            first = false;
        }
    }
    out
}

/// `cap_iab_from_text` (cap_text.c, CAP-IAB-0007): prefixes `!` (bound
/// drop), `^` (ambient + inheritable), `%` (inheritable only); a bare name
/// means inheritable; entries are `,`-separated with no whitespace.
pub fn cap_iab_from_text(text: &str) -> CapResult<CapIab> {
    let mut iab = CapIab::new();
    let mut s = text;
    let mut flags = 0u32;
    loop {
        let mut consumed_prefix = false;
        while let Some(ch) = s.chars().next() {
            match ch {
                '!' => flags |= 1u32 << CapIabVector::Bound as i32,
                '^' => {
                    flags |= (1u32 << CapIabVector::Inh as i32) | (1u32 << CapIabVector::Amb as i32)
                }
                '%' => flags |= 1u32 << CapIabVector::Inh as i32,
                _ => break,
            }
            s = &s[1..];
            consumed_prefix = true;
        }
        if s.is_empty() {
            return Ok(iab);
        }
        if flags == 0 && !consumed_prefix {
            flags = 1u32 << CapIabVector::Inh as i32;
        }
        let (c, rest) = match lookupname(s) {
            Some(v) => v,
            None => return Err(CapErrno::EINVAL),
        };
        s = rest;
        let o = (c as usize) >> 5;
        let mask = 1u32 << (c & 31);
        if flags & (1u32 << CapIabVector::Inh as i32) != 0 {
            iab.i[o] |= mask;
        }
        if flags & (1u32 << CapIabVector::Amb as i32) != 0 {
            iab.a[o] |= mask;
        }
        if flags & (1u32 << CapIabVector::Bound as i32) != 0 {
            iab.nb[o] |= mask;
        }
        if s.is_empty() {
            return Ok(iab);
        }
        if !s.starts_with(',') {
            return Err(CapErrno::EINVAL);
        }
        s = &s[1..];
        flags = 0;
    }
}

// ---------------------------------------------------------------------------
// cap_max_bits (CAP-PROC-0004)
// ---------------------------------------------------------------------------

use std::sync::OnceLock;

/// `cap_max_bits()`: the first unnamed capability (kernel `cap_last_cap` +
/// 1).  libcap probes it at startup (binary search over `cap_get_bound`,
/// falling back to `__CAP_BITS`); we read `/proc/sys/kernel/cap_last_cap`
/// with the same fallback (CAP-PROC-0004).
#[must_use]
pub fn cap_max_bits() -> usize {
    static MAX_BITS: OnceLock<usize> = OnceLock::new();
    *MAX_BITS.get_or_init(|| {
        if let Ok(v) = std::fs::read_to_string("/proc/sys/kernel/cap_last_cap") {
            if let Ok(n) = v.trim().parse::<usize>() {
                return n + 1;
            }
        }
        CAP_BITS
    })
}

// ---------------------------------------------------------------------------
// Process operations (CAP-PROC-0005..0021) — kernel-touching, behind
// platform::linux (unsafe inventory U-0001..U-0023)
// ---------------------------------------------------------------------------

use crate::platform::linux as lx;

/// `cap_get_proc()` (CAP-PROC-0005): the current process's capabilities via
/// capget (v3).
pub fn cap_get_proc() -> CapResult<CapState> {
    let mut caps = CapState::empty();
    let mut data = [0u32; 6];
    let mut header = lx::CapHeader {
        version: LINUX_CAPABILITY_VERSION_3,
        pid: 0,
    };
    lx::capget(&mut header, &mut data).map_err(CapErrno)?;
    caps.eff = [data[0], data[3]];
    caps.perm = [data[1], data[4]];
    caps.inh = [data[2], data[5]];
    Ok(caps)
}

/// `cap_get_pid(pid)` (CAP-PROC-0006).
pub fn cap_get_pid(pid: i32) -> CapResult<CapState> {
    let mut caps = CapState::empty();
    let mut data = [0u32; 6];
    let mut header = lx::CapHeader {
        version: LINUX_CAPABILITY_VERSION_3,
        pid,
    };
    lx::capget(&mut header, &mut data).map_err(CapErrno)?;
    caps.eff = [data[0], data[3]];
    caps.perm = [data[1], data[4]];
    caps.inh = [data[2], data[5]];
    Ok(caps)
}

/// `cap_set_proc(cap_d)` (CAP-PROC-0007): the v3 capset of the current
/// process.
pub fn cap_set_proc(caps: &CapState) -> CapResult<()> {
    let header = lx::CapHeader {
        version: LINUX_CAPABILITY_VERSION_3,
        pid: 0,
    };
    let data = [
        caps.eff[0],
        caps.perm[0],
        caps.inh[0],
        caps.eff[1],
        caps.perm[1],
        caps.inh[1],
    ];
    lx::capset(&header, &data).map_err(CapErrno)
}

/// `cap_get_bound(cap)` (CAP-PROC-0008): 1 when set, 0 when dropped, -1
/// (Err) when out of range — via prctl(PR_CAPBSET_READ).
pub fn cap_get_bound(cap: i32) -> CapResult<i32> {
    match lx::prctl(PR_CAPBSET_READ as i32, cap as i64, 0, 0, 0, 0) {
        Ok(v) => Ok(v as i32),
        Err(e) => Err(CapErrno(e)),
    }
}

/// `cap_drop_bound(cap)` (CAP-PROC-0009).
pub fn cap_drop_bound(cap: i32) -> CapResult<()> {
    lx::prctl(PR_CAPBSET_DROP as i32, cap as i64, 0, 0, 0, 0)
        .map(|_| ())
        .map_err(CapErrno)
}

/// `cap_get_ambient(cap)` (CAP-PROC-0010): prctl(PR_CAP_AMBIENT, IS_SET).
pub fn cap_get_ambient(cap: i32) -> CapResult<i32> {
    match lx::prctl(
        PR_CAP_AMBIENT as i32,
        PR_CAP_AMBIENT_IS_SET as i64,
        cap as i64,
        0,
        0,
        0,
    ) {
        Ok(v) => Ok(v as i32),
        Err(e) => Err(CapErrno(e)),
    }
}

/// `cap_set_ambient(cap, set)` (CAP-PROC-0011).
pub fn cap_set_ambient(cap: i32, set: CapFlagValue) -> CapResult<()> {
    let val = match set {
        CapFlagValue::Set => PR_CAP_AMBIENT_RAISE,
        CapFlagValue::Clear => PR_CAP_AMBIENT_LOWER,
    };
    lx::prctl(PR_CAP_AMBIENT as i32, val as i64, cap as i64, 0, 0, 0)
        .map(|_| ())
        .map_err(CapErrno)
}

/// `cap_reset_ambient()` (CAP-PROC-0012): probes the ambient set first (the
/// C works around a locked empty-set corner case), then CLEAR_ALL.
pub fn cap_reset_ambient() -> CapResult<()> {
    let mut c = 0i32;
    loop {
        match cap_get_ambient(c) {
            Ok(_) => c += 1,
            Err(_) => {
                // Ambient API locked/unsupported: the C returns 0 here.
                return Ok(());
            }
        }
    }
}

/// `cap_get_secbits()` (CAP-PROC-0013).
pub fn cap_get_secbits() -> CapResult<u32> {
    lx::prctl(PR_GET_SECUREBITS as i32, 0, 0, 0, 0, 0)
        .map(|v| v as u32)
        .map_err(CapErrno)
}

/// `cap_set_secbits(bits)` (CAP-PROC-0014).
pub fn cap_set_secbits(bits: u32) -> CapResult<()> {
    lx::prctl(PR_SET_SECUREBITS as i32, bits as i64, 0, 0, 0, 0)
        .map(|_| ())
        .map_err(CapErrno)
}

/// `cap_mode_name(flavor)` (CAP-PROC-0015).
#[must_use]
pub fn cap_mode_name(flavor: CapMode) -> &'static str {
    match flavor {
        CapMode::NoPriv => "NOPRIV",
        CapMode::Pure1eInit => "PURE1E_INIT",
        CapMode::Pure1e => "PURE1E",
        CapMode::Uncertain => "UNCERTAIN",
        CapMode::Hybrid => "HYBRID",
        _ => "UNKNOWN",
    }
}

/// `cap_get_mode()` (CAP-PROC-0016): the mode inferred from secbits,
/// ambient, capability state and bounding set.
pub fn cap_get_mode() -> CapMode {
    let secbits = cap_get_secbits().unwrap_or(0);
    if secbits == 0 {
        return CapMode::Hybrid;
    }
    if secbits & CAP_SECURED_BITS_BASIC != CAP_SECURED_BITS_BASIC {
        return CapMode::Uncertain;
    }
    // validate ambient is not set
    let mut c = 0i32;
    loop {
        match cap_get_ambient(c) {
            Ok(0) => c += 1,
            Ok(_) => return CapMode::Uncertain,
            Err(_) => {
                if c != 0 && secbits != CAP_SECURED_BITS_AMBIENT {
                    return CapMode::Uncertain;
                }
                break;
            }
        }
    }
    // compare working vs empty
    let working = cap_get_proc().unwrap_or_default();
    let empty = CapState::empty();
    let cf = empty.compare(&working);
    if cf & LIBCAP_INH != 0 {
        return CapMode::Pure1e;
    }
    if cf & LIBCAP_PER != 0 || cf & LIBCAP_EFF != 0 {
        return CapMode::Pure1eInit;
    }
    let mut c = 0i32;
    loop {
        match cap_get_bound(c) {
            Ok(0) => c += 1,
            Ok(_) => return CapMode::Pure1eInit,
            Err(_) => break,
        }
    }
    CapMode::NoPriv
}

/// `cap_set_mode(flavor)` (CAP-PROC-0017): a faithful transcription of
/// `_cap_set_mode` (including the side effect of clearing CAP_EFFECTIVE at
/// the end, whether or not the mode change succeeded).
pub fn cap_set_mode(flavor: CapMode) -> CapResult<()> {
    let mut secbits = CAP_SECURED_BITS_AMBIENT;
    let mut working = cap_get_proc()?;
    let raise_setpcap = [cap::SETPCAP];
    let mut ret = working
        .set_flag(CapFlag::Effective, &raise_setpcap, CapFlagValue::Set)
        .and_then(|_| cap_set_proc(&working));
    if ret.is_ok() {
        match flavor {
            CapMode::NoPriv | CapMode::Pure1eInit => {
                working.clear_flag(CapFlag::Inheritable);
            }
            _ => {}
        }
        match flavor {
            CapMode::NoPriv | CapMode::Pure1e | CapMode::Pure1eInit => {
                if cap_get_ambient(cap::CHOWN).is_err() {
                    secbits = CAP_SECURED_BITS_BASIC;
                } else {
                    ret = cap_reset_ambient();
                }
                if ret.is_ok() {
                    ret = cap_set_secbits(secbits);
                }
                if flavor == CapMode::NoPriv {
                    let mut c = 0i32;
                    while cap_get_bound(c).is_ok() {
                        let _ = cap_drop_bound(c);
                        c += 1;
                    }
                    working.clear_flag(CapFlag::Permitted);
                    let _ = lx::prctl(PR_SET_NO_NEW_PRIVS as i32, 1, 0, 0, 0, 0);
                }
            }
            CapMode::Hybrid => {
                ret = cap_set_secbits(0);
            }
            CapMode::Uncertain => {
                return Err(CapErrno::EINVAL);
            }
        }
    }
    working.clear_flag(CapFlag::Effective);
    let _ = cap_set_proc(&working);
    ret
}

/// `cap_setuid(uid)` (CAP-PROC-0018): raise CAP_SETUID effective, KEEPCAPS
/// on, setuid, KEEPCAPS off, clear effective (side effect).
pub fn cap_setuid(uid: u32) -> CapResult<()> {
    let raise = [cap::SETUID];
    let mut working = cap_get_proc()?;
    working.set_flag(CapFlag::Effective, &raise, CapFlagValue::Set)?;
    let _ = lx::prctl(PR_SET_KEEPCAPS as i32, 1, 0, 0, 0, 0);
    let ret = cap_set_proc(&working).and_then(|_| lx::setuid(uid).map_err(CapErrno));
    let olderrno = ret.as_ref().err().copied();
    let _ = lx::prctl(PR_SET_KEEPCAPS as i32, 0, 0, 0, 0, 0);
    working.clear_flag(CapFlag::Effective);
    let _ = cap_set_proc(&working);
    match olderrno {
        Some(e) => Err(e),
        None => ret,
    }
}

/// `cap_setgroups(gid, groups)` (CAP-PROC-0019): raise CAP_SETGID effective,
/// setgid + setgroups, clear effective (side effect).
pub fn cap_setgroups(gid: u32, groups: &[u32]) -> CapResult<()> {
    let raise = [cap::SETGID];
    let mut working = cap_get_proc()?;
    working.set_flag(CapFlag::Effective, &raise, CapFlagValue::Set)?;
    let ret = cap_set_proc(&working)
        .and_then(|_| lx::setgid(gid).map_err(CapErrno))
        .and_then(|_| lx::setgroups(groups).map_err(CapErrno));
    let olderrno = ret.as_ref().err().copied();
    working.clear_flag(CapFlag::Effective);
    let _ = cap_set_proc(&working);
    match olderrno {
        Some(e) => Err(e),
        None => ret,
    }
}

/// `cap_iab_get_proc()` (CAP-PROC-0020): IAB from the current process
/// (inheritable via capget, bounding/ambient via prctl).
pub fn cap_iab_get_proc() -> CapResult<CapIab> {
    let mut iab = CapIab::new();
    let current = cap_get_proc()?;
    iab.fill(CapIabVector::Inh, &current, CapFlag::Inheritable)?;
    let mut c = cap_max_bits() as i32;
    while c > 0 {
        c -= 1;
        let o = (c as usize) >> 5;
        let mask = 1u32 << (c & 31);
        if cap_get_bound(c) == Ok(0) {
            iab.nb[o] |= mask;
        }
        if cap_get_ambient(c) == Ok(1) {
            iab.a[o] |= mask;
        }
    }
    Ok(iab)
}

/// `cap_iab_set_proc(iab)` (CAP-PROC-0021): apply I to the inheritable set
/// (raising CAP_SETPCAP effective as needed), reset ambient, raise ambient,
/// drop bounding bits, then restore.
pub fn cap_iab_set_proc(iab: &CapIab) -> CapResult<()> {
    let temp = cap_get_proc()?;
    let mut raising = 0u32;
    let mut check_bound = false;
    for i in 0..2 {
        let new_i = iab.i[i];
        let old_ip = temp.inh[i] | temp.perm[i];
        raising |= new_i & !old_ip;
        if iab.nb[i] != 0 {
            check_bound = true;
        }
    }
    if check_bound {
        let mut c = cap_max_bits() as i32;
        while c > 0 {
            c -= 1;
            let o = (c as usize) >> 5;
            let mask = 1u32 << (c & 31);
            if iab.nb[o] & mask != 0 && cap_get_bound(c) == Ok(1) {
                raising = 1;
                check_bound = true;
                break;
            }
        }
    }
    let mut working = temp.dup();
    if raising != 0 {
        working.set_flag(CapFlag::Effective, &[cap::SETPCAP], CapFlagValue::Set)?;
    }
    cap_set_proc(&working)?;
    let mut ret = cap_reset_ambient();
    if ret.is_ok() {
        let mut c = cap_max_bits() as i32;
        while c > 0 {
            c -= 1;
            let o = (c as usize) >> 5;
            let mask = 1u32 << (c & 31);
            if iab.a[o] & mask != 0 {
                ret = cap_set_ambient(c, CapFlagValue::Set);
                if ret.is_err() {
                    break;
                }
            }
            if check_bound && iab.nb[o] & mask != 0 {
                ret = cap_drop_bound(c);
                if ret.is_err() {
                    break;
                }
            }
        }
    }
    let _ = cap_set_proc(&temp);
    ret
}

// ---------------------------------------------------------------------------
// File operations (CAP-FILE-0001..0012) — the security.capability xattr
// ---------------------------------------------------------------------------

fn vfs_caps_save(caps: &CapState) -> CapResult<(Vec<u8>, u32)> {
    // _fcaps_save: v2/v3 magic chosen by the header version (we always use
    // v3 internally); rootid != 0 forces revision 3.
    let mut magic: u32 = VFS_CAP_REVISION_2;
    let mut tocopy = 2usize;
    let mut bytes = XATTR_CAPS_SZ_2;
    if caps.rootid != 0 {
        magic = VFS_CAP_REVISION_3;
        tocopy = 2;
        bytes = XATTR_CAPS_SZ_3;
    }
    // bits beyond tocopy must be clear
    for i in tocopy..2 {
        if caps.eff[i] | caps.inh[i] | caps.perm[i] != 0 {
            return Err(CapErrno::EINVAL);
        }
    }
    let mut eff_not_zero = 0u32;
    for i in 0..tocopy {
        eff_not_zero |= caps.eff[i];
    }
    for i in 0..tocopy {
        // The C is `(~eff) & (perm|inh)` as a pure bitmask (cap_file.c
        // _fcaps_save): when ANY effective bit is set, every effective bit
        // must be covered by permitted|inheritable.  NB: the `!= 0` applies
        // to the whole mask expression, not to (perm|inh) alone — the former
        // spelling evaluated `(perm|inh) != 0` -> 1 and then `!eff & 1`,
        // spuriously rejecting every non-empty permitted set (CAP-FILE-0002).
        if eff_not_zero != 0 && (!caps.eff[i] & (caps.perm[i] | caps.inh[i])) != 0 {
            return Err(CapErrno::EINVAL);
        }
    }
    // Kernel vfs_ns_cap_data layout (cap_file.c _fcaps_save / uapi/linux/
    // capability.h): magic_etc FIRST, then data[0..2] (permitted,
    // inheritable each), then the rootid LAST for revision 3.  The rootid
    // must not be emitted in front of magic_etc — the kernel rejects that
    // order with EINVAL (CAP-FILE-0010).
    let mut out = Vec::with_capacity(bytes);
    let magic_etc = if eff_not_zero == 0 {
        magic
    } else {
        magic | VFS_CAP_FLAGS_EFFECTIVE
    };
    out.extend_from_slice(&magic_etc.to_le_bytes());
    for i in 0..tocopy {
        out.extend_from_slice(&caps.perm[i].to_le_bytes());
        out.extend_from_slice(&caps.inh[i].to_le_bytes());
    }
    if magic == VFS_CAP_REVISION_3 {
        out.extend_from_slice(&caps.rootid.to_le_bytes());
    }
    Ok((out, magic_etc))
}

fn vfs_caps_load(raw: &[u8]) -> CapResult<CapState> {
    // _fcaps_load: magic_etc is the FIRST field of vfs_ns_cap_data; the
    // revision determines the total size; rootid (v3) is the TRAILING 4
    // bytes.  cap_file.c reads magic_etc then validates the exact size.
    if raw.len() < 4 {
        return Err(CapErrno::EINVAL);
    }
    let magic_etc = u32::from_le_bytes([raw[0], raw[1], raw[2], raw[3]]);
    let rev = magic_etc & VFS_CAP_REVISION_MASK;
    let (tocopy, bytes) = match rev {
        VFS_CAP_REVISION_1 => (1usize, XATTR_CAPS_SZ_1),
        VFS_CAP_REVISION_2 => (2usize, XATTR_CAPS_SZ_2),
        VFS_CAP_REVISION_3 => (2usize, XATTR_CAPS_SZ_3),
        _ => return Err(CapErrno::EINVAL),
    };
    if raw.len() != bytes {
        return Err(CapErrno::EINVAL);
    }
    let mut caps = CapState::empty();
    let data_start = 4;
    for i in 0..tocopy {
        let off = data_start + i * 8;
        caps.perm[i] = u32::from_le_bytes([raw[off], raw[off + 1], raw[off + 2], raw[off + 3]]);
        caps.inh[i] = u32::from_le_bytes([raw[off + 4], raw[off + 5], raw[off + 6], raw[off + 7]]);
        if magic_etc & VFS_CAP_FLAGS_EFFECTIVE != 0 {
            caps.eff[i] = caps.inh[i] | caps.perm[i];
        }
    }
    if rev == VFS_CAP_REVISION_3 {
        caps.rootid = u32::from_le_bytes([
            raw[bytes - 4],
            raw[bytes - 3],
            raw[bytes - 2],
            raw[bytes - 1],
        ]);
    }
    Ok(caps)
}

/// `cap_get_file(path)` (CAP-FILE-0003): read the security.capability xattr.
pub fn cap_get_file(path: &str) -> CapResult<CapState> {
    let cpath = CString::new(path).map_err(|_| CapErrno::EINVAL)?;
    let cname = CString::new(XATTR_NAME_CAPS).unwrap();
    let mut buf = vec![0u8; 128];
    let n = lx::getxattr(&cpath, &cname, &mut buf).map_err(CapErrno)?;
    buf.truncate(n);
    vfs_caps_load(&buf)
}

/// `cap_set_file(path, caps)` (CAP-FILE-0004): write (or remove when None)
/// the xattr.  Mirrors cap_file.c `cap_set_file` exactly: first try
/// `O_RDONLY|O_NOFOLLOW` and operate on the fd; if the file content is not
/// readable, fall back to `O_PATH|O_NOFOLLOW` plus the `/proc/self/fd/N`
/// path dance (the O_PATH fd pins the origin file against TOCTOU; the
/// xattr ops go through the /proc path because fsetxattr on an O_PATH fd
/// fails with EBADF).
pub fn cap_set_file(path: &str, caps: Option<&CapState>) -> CapResult<()> {
    let cpath = CString::new(path).map_err(|_| CapErrno::EINVAL)?;
    if let Ok(fd) = lx::open(&cpath, libc::O_RDONLY | libc::O_NOFOLLOW) {
        let r = cap_set_fd(fd, caps);
        lx::close(fd);
        return r;
    }
    // fallback: unreadable file (e.g. mode 000) — O_PATH + /proc/self/fd
    let fd = lx::open(&cpath, libc::O_PATH | libc::O_NOFOLLOW).map_err(CapErrno)?;
    let mode = lx::fstat_mode(fd).map_err(CapErrno)?;
    let s_ift = 0o170000u32;
    let s_iflnk = 0o120000u32;
    let s_ifreg = 0o100000u32;
    if mode & s_ift == s_iflnk || mode & s_ift != s_ifreg {
        lx::close(fd);
        return Err(CapErrno::EINVAL);
    }
    let fdpath = CString::new(format!("/proc/self/fd/{}", fd)).unwrap();
    let cname = CString::new(XATTR_NAME_CAPS).unwrap();
    let r = match caps {
        None => lx::removexattr(&fdpath, &cname).map_err(CapErrno),
        Some(c) => {
            let (raw, _) = vfs_caps_save(c)?;
            lx::setxattr(&fdpath, &cname, &raw).map_err(CapErrno)
        }
    };
    lx::close(fd);
    r
}

/// `cap_get_fd(fd)` (CAP-FILE-0005).
pub fn cap_get_fd(fd: i32) -> CapResult<CapState> {
    let cname = CString::new(XATTR_NAME_CAPS).unwrap();
    let mut buf = vec![0u8; 128];
    let n = lx::fgetxattr(fd, &cname, &mut buf).map_err(CapErrno)?;
    buf.truncate(n);
    vfs_caps_load(&buf)
}

/// `cap_set_fd(fd, caps)` (CAP-FILE-0006): the C requires a regular
/// non-symlink file (fstat check), then fsetxattr/fremovexattr.
pub fn cap_set_fd(fd: i32, caps: Option<&CapState>) -> CapResult<()> {
    let mode = lx::fstat_mode(fd).map_err(CapErrno)?;
    let s_ift = 0o170000u32;
    let s_iflnk = 0o120000u32;
    let s_ifreg = 0o100000u32;
    if mode & s_ift == s_iflnk || mode & s_ift != s_ifreg {
        return Err(CapErrno::EINVAL);
    }
    let cname = CString::new(XATTR_NAME_CAPS).unwrap();
    match caps {
        None => lx::fremovexattr(fd, &cname).map_err(CapErrno),
        Some(c) => {
            let (raw, _) = vfs_caps_save(c)?;
            lx::fsetxattr(fd, &cname, &raw).map_err(CapErrno)
        }
    }
}

/// `cap_get_nsowner(caps)` (CAP-FILE-0007).
#[must_use]
pub fn cap_get_nsowner(caps: &CapState) -> u32 {
    caps.rootid
}

/// `cap_set_nsowner(caps, rootuid)` (CAP-FILE-0008).
pub fn cap_set_nsowner(caps: &mut CapState, rootuid: u32) {
    caps.rootid = rootuid;
}

/// Probe accessor (CAP-FILE-0009): the raw VFS xattr bytes + magic_etc for
/// the given state, used by the cap-file probe court to hex-dump the xattr.
pub fn vfs_save_for_probe(c: &CapState) -> CapResult<(Vec<u8>, u32)> {
    vfs_caps_save(c)
}

// ---------------------------------------------------------------------------
// Launcher (CAP-LAUNCH-0001..0012) — fork/exec wrapper
// ---------------------------------------------------------------------------

/// A `cap_launch_t` equivalent: the attributes of a `cap_launch` invocation.
#[derive(Debug, Clone, Default)]
pub struct CapLauncher {
    pub uid: Option<u32>,
    pub gid: Option<u32>,
    pub groups: Option<Vec<u32>>,
    pub mode: Option<CapMode>,
    pub iab: Option<CapIab>,
    pub chroot: Option<String>,
}

/// `cap_launch(attr, argv, envp)` (CAP-LAUNCH-0012): fork, apply the
/// attribute changes in the child, execve; report child setup failures via
/// the pipe.  Returns the child pid (the caller waitpids).
pub fn cap_launch(
    attr: &CapLauncher,
    arg0: &str,
    argv: &[String],
    envp: &[String],
) -> CapResult<i32> {
    let (ps_r, ps_w) = lx::pipe2(libc::O_CLOEXEC).map_err(CapErrno)?;
    let child = lx::fork().map_err(CapErrno)?;
    if child == 0 {
        // child
        lx::close(ps_r);
        let _ = lx::prctl(PR_SET_NAME as i32, 0, 0, 0, 0, 0);
        let result = child_setup(attr, arg0, argv, envp);
        let errno = match result {
            Ok(()) => 0,
            Err(e) => e.0,
        };
        // communicate errno to the parent
        let bytes = errno.to_ne_bytes();
        let _ = lx::write_fd(ps_w, &bytes);
        lx::close(ps_w);
        std::process::exit(1);
    }
    lx::close(ps_w);
    if child < 0 {
        lx::close(ps_r);
        return Err(CapErrno(
            std::io::Error::last_os_error().raw_os_error().unwrap_or(0),
        ));
    }
    // parent: wait for the child's setup report
    let mut buf = [0u8; 4];
    match lx::read_fd(ps_r, &mut buf) {
        Ok(0) => {
            // exec succeeded (child is gone or running)
            lx::close(ps_r);
            Ok(child)
        }
        Ok(_) => {
            let e = i32::from_ne_bytes(buf);
            let _ = lx::waitpid(child);
            lx::close(ps_r);
            Err(CapErrno(e))
        }
        Err(_) => {
            lx::close(ps_r);
            Ok(child)
        }
    }
}

fn child_setup(attr: &CapLauncher, arg0: &str, argv: &[String], envp: &[String]) -> CapResult<()> {
    if let Some(uid) = attr.uid {
        cap_setuid(uid)?;
    }
    if let Some(gid) = attr.gid {
        match &attr.groups {
            Some(g) => cap_setgroups(gid, g)?,
            None => cap_setgroups(gid, &[])?,
        }
    }
    if let Some(mode) = attr.mode {
        cap_set_mode(mode)?;
    }
    if let Some(iab) = &attr.iab {
        cap_iab_set_proc(iab)?;
    }
    if let Some(root) = &attr.chroot {
        let c = CString::new(root.as_str()).map_err(|_| CapErrno::EINVAL)?;
        lx::chroot(&c).map_err(CapErrno)?;
        lx::chdir_root().map_err(CapErrno)?;
    }
    let c_arg0 = CString::new(arg0).map_err(|_| CapErrno::EINVAL)?;
    let c_argv: Vec<CString> = argv
        .iter()
        .map(|a| CString::new(a.as_str()))
        .collect::<Result<_, _>>()
        .map_err(|_| CapErrno::EINVAL)?;
    let c_envp: Vec<CString> = envp
        .iter()
        .map(|a| CString::new(a.as_str()))
        .collect::<Result<_, _>>()
        .map_err(|_| CapErrno::EINVAL)?;
    lx::execve(&c_arg0, &c_argv, &c_envp).map_err(CapErrno)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn names_oracle_vectors() {
        // probe-libcap.c CAP-NAME results (oracle libcap 2.78).
        assert_eq!(cap_from_name("chown"), Err(CapErrno::EINVAL));
        assert_eq!(cap_from_name("cap_chown"), Ok(0));
        assert_eq!(cap_from_name("CAP_CHOWN"), Ok(0));
        assert_eq!(cap_from_name("ChOwN"), Err(CapErrno::EINVAL));
        assert_eq!(cap_from_name("12"), Ok(12));
        assert_eq!(cap_from_name("0x2"), Ok(2));
        assert_eq!(cap_from_name("kill"), Err(CapErrno::EINVAL));
        assert_eq!(cap_from_name("cap_kill"), Ok(5));
        assert_eq!(cap_from_name("nonsense"), Err(CapErrno::EINVAL));
        assert_eq!(cap_from_name("41"), Ok(41));
        assert_eq!(cap_from_name("64"), Err(CapErrno::EINVAL));
        assert_eq!(cap_from_name("chownx"), Err(CapErrno::EINVAL));
        assert_eq!(cap_from_name("chow"), Err(CapErrno::EINVAL));
        assert_eq!(cap_to_name(0), "cap_chown");
        assert_eq!(cap_to_name(12), "cap_net_admin");
        assert_eq!(cap_to_name(41), "41");
        assert_eq!(cap_to_name(64), "64");
        assert_eq!(cap_to_name(-1), "4294967295");
    }

    #[test]
    fn text_oracle_vectors() {
        // probe-libcap.c from_text → cap_to_text round-trips.
        for (input, expected) in [
            ("cap_kill=ep", "cap_kill=ep"),
            (
                "cap_kill=ep cap_net_bind_service+i",
                "cap_net_bind_service=i cap_kill+ep",
            ),
            ("=ep", "=ep"),
            ("all=eip", "=eip"),
            ("=ep cap_net_raw+p", "=ep"),
            (
                "cap_chown,cap_net_bind_service+eip",
                "cap_chown,cap_net_bind_service=eip",
            ),
            ("5=ep", "cap_kill=ep"),
            ("cap_kill=ep cap_kill+ip", "cap_kill=eip"),
            ("cap_kill=ep cap_kill-i", "cap_kill=ep"),
            ("=eip cap_kill-e", "=eip cap_kill-e"),
            ("cap_kill+ep", "cap_kill=ep"),
            ("= cap_kill+ep", "cap_kill=ep"),
            ("cap_kill=", "="),
            ("cap_kill= cap_net_raw+ep", "cap_net_raw=ep"),
            ("=ep ", "=ep"),
            ("41+ep", "= 41+ep"),
        ] {
            let c = cap_from_text(input).unwrap_or_else(|e| panic!("from_text({input}): {e}"));
            let (txt, _len) = cap_to_text(&c);
            assert_eq!(txt, expected, "from_text({input})");
        }
        for bad in [
            "!cap_kill",
            "cap_kill+",
            "cap_unknownname+ep",
            "cap_kill==ep",
            "cap_kill=eip,",
            "cap_kill=ep,",
        ] {
            assert_eq!(
                cap_from_text(bad),
                Err(CapErrno::EINVAL),
                "from_text({bad})"
            );
        }
    }

    #[test]
    fn flag_and_compare_vectors() {
        let mut a = CapState::empty();
        let b = CapState::empty();
        assert_eq!(a.compare(&b), 0);
        a.set_flag(
            CapFlag::Effective,
            &[cap::CHOWN, cap::NET_BIND_SERVICE],
            CapFlagValue::Set,
        )
        .unwrap();
        assert_eq!(a.compare(&a), 0);
        assert_eq!(a.compare(&b), LIBCAP_EFF);
        let mut bb = CapState::empty();
        bb.set_flag(
            CapFlag::Effective,
            &[cap::CHOWN, cap::NET_BIND_SERVICE],
            CapFlagValue::Set,
        )
        .unwrap();
        bb.set_flag(CapFlag::Permitted, &[cap::CHOWN], CapFlagValue::Set)
            .unwrap();
        assert_eq!(a.compare(&bb), LIBCAP_PER);
        assert_eq!(
            a.get_flag(cap::CHOWN, CapFlag::Effective),
            Ok(CapFlagValue::Set)
        );
        assert_eq!(
            a.get_flag(cap::CHOWN, CapFlag::Permitted),
            Ok(CapFlagValue::Clear)
        );
        // out-of-range entries are skipped without error
        assert_eq!(
            a.set_flag(CapFlag::Effective, &[500], CapFlagValue::Set),
            Ok(())
        );
        // empty array is EINVAL
        assert_eq!(
            a.set_flag(CapFlag::Effective, &[], CapFlagValue::Set),
            Err(CapErrno::EINVAL)
        );
        a.clear();
        assert_eq!(
            a.get_flag(cap::CHOWN, CapFlag::Effective),
            Ok(CapFlagValue::Clear)
        );
    }

    #[test]
    fn external_format_vectors() {
        // probe-libcap.c dump_ext: magic + len + eff/perm/inh bytes.
        let mut e = CapState::empty();
        e.set_flag(
            CapFlag::Effective,
            &[cap::CHOWN, cap::NET_BIND_SERVICE],
            CapFlagValue::Set,
        )
        .unwrap();
        let mut buf = vec![0u8; 64];
        let n = cap_copy_ext(&mut buf, &e).unwrap();
        assert_eq!(n, 29);
        assert_eq!(&buf[0..5], &[0x90, 0xc2, 0x01, 0x51, 0x08]);
        // bytes are interleaved per set: bytes[j][set] at offset 5 + j*3 +
        // set.  eff = 0x401 (cap_chown + cap_net_bind_service): byte0 = 0x01
        // (offset 5), byte1 = 0x04 (offset 8); perm/inh all zero.
        assert_eq!(buf[5], 0x01);
        assert_eq!(buf[6], 0x00); // perm byte0
        assert_eq!(buf[7], 0x00); // inh byte0
        assert_eq!(buf[8], 0x04); // eff byte1
        assert!(buf[9..29].iter().all(|&b| b == 0));
        // round-trip
        let g = cap_copy_int(&buf).unwrap();
        assert_eq!(e.compare(&g), 0);
        // bad magic
        buf[0] ^= 0xff;
        assert_eq!(cap_copy_int(&buf), Err(CapErrno::EINVAL));
        // too-small destination
        let mut tiny = [0u8; 4];
        assert_eq!(cap_copy_ext(&mut tiny, &e), Err(CapErrno::EINVAL));
    }

    #[test]
    fn iab_text_vectors() {
        let mut iab = CapIab::new();
        assert_eq!(cap_iab_to_text(&iab), "");
        iab.set_vector(CapIabVector::Inh, cap::CHOWN, CapFlagValue::Set)
            .unwrap();
        assert_eq!(cap_iab_to_text(&iab), "cap_chown");
        iab.set_vector(CapIabVector::Amb, cap::NET_RAW, CapFlagValue::Set)
            .unwrap();
        assert_eq!(cap_iab_to_text(&iab), "cap_chown,^cap_net_raw");
        iab.set_vector(CapIabVector::Bound, cap::SYS_ADMIN, CapFlagValue::Set)
            .unwrap();
        assert_eq!(
            cap_iab_to_text(&iab),
            "cap_chown,^cap_net_raw,!cap_sys_admin"
        );
        // spaces are rejected (comma-separated only, CAP-IAB-0007)
        assert_eq!(
            cap_iab_from_text("^cap_chown cap_kill !cap_net_raw"),
            Err(CapErrno::EINVAL)
        );
        let parsed = cap_iab_from_text("cap_chown,^cap_net_raw,!cap_sys_admin").unwrap();
        assert_eq!(parsed.compare(&iab), 0);
    }

    #[test]
    fn file_format_roundtrip() {
        let mut c = CapState::empty();
        c.set_flag(
            CapFlag::Permitted,
            &[cap::NET_BIND_SERVICE],
            CapFlagValue::Set,
        )
        .unwrap();
        c.set_flag(
            CapFlag::Effective,
            &[cap::NET_BIND_SERVICE],
            CapFlagValue::Set,
        )
        .unwrap();
        let (raw, magic) = vfs_caps_save(&c).unwrap();
        assert_eq!(magic, VFS_CAP_REVISION_2 | VFS_CAP_FLAGS_EFFECTIVE);
        assert_eq!(raw.len(), XATTR_CAPS_SZ_2);
        // Kernel byte layout (CAP-FILE-0010): magic_etc first, then per-u32
        // permitted+inheritable.  These are the exact bytes captured from the
        // C libcap probe in court CAP-FILE-0001 (xattr(20) line).
        assert_eq!(
            raw,
            vec![
                0x01, 0x00, 0x00, 0x02, // magic_etc = REV2|EFFECTIVE (LE)
                0x00, 0x04, 0x00, 0x00, // data[0].permitted  = 1<<10
                0x00, 0x00, 0x00, 0x00, // data[0].inheritable
                0x00, 0x00, 0x00, 0x00, // data[1].permitted
                0x00, 0x00, 0x00, 0x00, // data[1].inheritable
            ]
        );
        let loaded = vfs_caps_load(&raw).unwrap();
        assert_eq!(c.compare(&loaded), 0);
        // rootid forces revision 3 (with the effective flag since eff is set)
        c.rootid = 1000;
        let (raw, magic) = vfs_caps_save(&c).unwrap();
        assert_eq!(magic, VFS_CAP_REVISION_3 | VFS_CAP_FLAGS_EFFECTIVE);
        assert_eq!(raw.len(), XATTR_CAPS_SZ_3);
        // v3 kernel layout: rootid is the TRAILING field (CAP-FILE-0010);
        // bytes below are the captured C-oracle xattr(24) line (rootid=1000
        // appears as the last four bytes e8 03 00 00).
        assert_eq!(
            raw,
            vec![
                0x01, 0x00, 0x00, 0x03, // magic_etc = REV3|EFFECTIVE (LE)
                0x00, 0x04, 0x00, 0x00, // data[0].permitted
                0x00, 0x00, 0x00, 0x00, // data[0].inheritable
                0x00, 0x00, 0x00, 0x00, // data[1].permitted
                0x00, 0x00, 0x00, 0x00, // data[1].inheritable
                0xe8, 0x03, 0x00, 0x00, // rootid = 1000 (LE, trailing)
            ]
        );
        let loaded = vfs_caps_load(&raw).unwrap();
        assert_eq!(c.compare(&loaded), 0);
        assert_eq!(loaded.rootid, 1000);
        // Parse the exact 24-byte xattr the C probe leaves on disk when it
        // writes the v3/rootid form with NO effective bits (magic without the
        // effective flag: 00 00 00 03), also captured in CAP-FILE-0001.
        let c_v3_noeff: [u8; 24] = [
            0x00, 0x00, 0x00, 0x03, 0x00, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xe8, 0x03, 0x00, 0x00,
        ];
        let l2 = vfs_caps_load(&c_v3_noeff).unwrap();
        assert_eq!(l2.rootid, 1000);
        assert_eq!(
            l2.get_flag(cap::NET_BIND_SERVICE, CapFlag::Permitted),
            Ok(CapFlagValue::Set)
        );
        assert_eq!(
            l2.get_flag(cap::NET_BIND_SERVICE, CapFlag::Effective),
            Ok(CapFlagValue::Clear)
        );
    }
}
